name: $(BuildID).$(Date:yyMMdd)$(Rev:.r)

trigger:
- master

variables:
  nodeVersion: '>=10.15.3'
  npmVersion: 'latest'

jobs:
- job: Build_Windows
  pool:
    vmImage: 'windows-2019'
    demands: npm
  steps:
    - template: templates/setup-environment.yml
    - template: templates/install-dependencies.yml
    - template: templates/compile.yml
    - script: |
        node node_modules/vscode/bin/test
      displayName: 'Run tests'

- job: Build_Ubuntu
  pool:
    vmImage: 'ubuntu-16.04'
    demands: npm
  steps:
    - template: templates/setup-environment.yml
    - template: templates/install-dependencies.yml
    - template: templates/compile.yml
    - script: |
        set -e
        /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
        disown -ar
      displayName: 'Start xvfb'
    - script: 'node node_modules/vscode/bin/test'
      displayName: 'Run tests'
      env:
        DISPLAY: :10

- job: Build_macOS
  pool:
    vmImage: 'macOS-10.14'
    demands: npm
  steps:
    - template: templates/setup-environment.yml
    - template: templates/install-dependencies.yml
    - template: templates/compile.yml
    - script: |
        node node_modules/vscode/bin/test
      displayName: 'Run tests'

- job: Publish
  dependsOn:
  - Build_Windows
  - Build_Ubuntu
  - Build_macOS
  steps:
    - template: templates/package-artifact.yml
